import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdir,writeFile,readFile} from 'node:fs/promises';
import {join,parse} from 'node:path';
import {fixture,settle} from './fixtures.mjs';
import {createDraft} from '../core/workflow-schema.mjs';
import {canonicalJSON,digest} from '../core/workflow-revisions.mjs';
import {writeDurableJSON} from '../core/workflow-events.mjs';
import {HostToolRunner,validateHostStorageCapabilities,requireHostStorageEffects} from '../core/execution/host-tool-runner.mjs';
import {externalHostToolDescriptors} from '../lib/external-host-tools.mjs';
const identity={name:'fixture-private-storage',version:'1',sha256:digest('fixture-private-storage')};
const contract={id:'storage_write',identity,argv:[],env_allow:[],input_schema:{type:'object',additionalProperties:false,properties:{},required:[]},output_schema:{type:'object',additionalProperties:false,properties:{done:{type:'boolean'}},required:['done']},permissions:{network:false,read_paths:['.'],write_paths:['.']},output_cap_bytes:131072,deadline_ms:5000,idempotency:{mode:'reconcile_required'}};
const graph=()=>({...createDraft('storage-fixture','Host private storage fixture'),status:'ready',host_tools:[contract],inputs_schema:contract.input_schema,outputs_schema:contract.output_schema,output_bindings:{done:'/nodes/final/output/done'},finalization:{required:true,node_id:'final'},nodes:[{id:'start',type:'start'},{id:'commit',type:'tool',executor:{kind:'tool',tool:contract.id},access:'bounded_write',path_scope:{binding:'run.allowed_paths'},retry:{max_attempts:1},approval:{required:false},input_bindings:{},outputs_schema:contract.output_schema},{id:'final',type:'tool',executor:{kind:'tool',tool:contract.id},access:'bounded_write',path_scope:{binding:'run.allowed_paths'},retry:{max_attempts:1},approval:{required:false},input_bindings:{},outputs_schema:contract.output_schema,completion_contract:{on_missing:'block',outcome:'decision',fail_on_false:['done']}},{id:'end',type:'end'}],edges:[{id:'begin',source:'start',target:'commit'},{id:'finish',source:'commit',target:'final'},{id:'end',source:'final',target:'end'}]});
async function setup(t,{declare=true}={}){
 const f=await fixture(t),files=['course.sqlite','course.sqlite-wal','course.sqlite-shm'].map(name=>join(f.root,name)),journal=join(f.root,'private-journal');await mkdir(journal);let calls=0;
 const capabilities={write_files:files,write_directories:[journal]};
 const domain={identity,contract,attestation:{qualified:true,cancellable:true,effect_observation:true,tool_identity:identity,broker_id:'fixture-storage-broker',evidence_sha256:digest('fixture-qualification'),...(declare?{storage_capabilities:capabilities}:{})},execute:async request=>{calls++;await request.authorize?.();await Promise.all(files.map(path=>writeFile(path,'database-write-'+calls)));const record=join(journal,'request-'+calls+'.json');await writeFile(record,'durable request');await writeFile(join(f.workspace,'experiment.json'),'saved');return {exit_code:0,output:{done:true},effects:{observed:true,changed_paths:['experiment.json'],outside_paths:[...files,record],artifacts:[]}};},cancel:async()=>({termination_confirmed:true,evidence:[{kind:'closed',sha256:digest('closed')}],effects:{observed:true,changed_paths:[],outside_paths:[],artifacts:[]}})};
 f.host.getHostTools=()=>({[contract.id]:domain});await f.service.refreshContext();await f.service.call('create_workflow',{workflow:graph()});return {...f,domain,files,journal,capabilities,calls:()=>calls};
}
test('real workflow engine retains separately qualified DB/WAL/SHM/journal effects without widening the child grant',async t=>{
 const f=await setup(t);const run=await f.service.call('run',{workflow_id:'storage-fixture',workspace:f.workspace,access:'bounded_write',allowed_paths:['.'],inputs:{},detached_host:false});await settle(f.service,run.run_id);const r=await f.service.runtime.runs.read(run.run_id);assert.equal(r.state.status,'succeeded');assert.equal(f.calls(),2);assert.deepEqual(r.state.permissions.allowed_paths,['.']);assert.equal(r.state.permissions.workspace,f.workspace);
 const attempt=r.state.nodes.commit.attempts[0];assert.deepEqual(attempt.completion.outside_paths,[...f.files,join(f.journal,'request-1.json')]);assert.deepEqual(attempt.host_tool.receipt.broker.storage_capabilities,f.capabilities);assert.equal(attempt.host_tool.receipt.output_sha256,digest(canonicalJSON(attempt.completion.structured_output)));
 assert.equal(Object.hasOwn(externalHostToolDescriptors({[contract.id]:f.domain})[0].contract.permissions,'storage_capabilities'),false);
});
test('legacy succeeded delivery collects the same immutable receipt after exact controller recovery with zero re-execution',async t=>{
 const f=await setup(t,{declare:false});const run=await f.service.runtime.start({workflow_id:'storage-fixture',workspace:f.workspace,access:'bounded_write',allowed_paths:['.'],main_actor:f.mainSession,inputs:{}});await writeDurableJSON(join(f.service.runtime.runs.directory(run.run_id),'pi-controller.json'),{control_token:run.control_token});const args={control_token:run.control_token,...await f.service.runtime.claimNode(run.run_id,{control_token:run.control_token,node_id:'commit',owner:'fixture',request_id:'one-delivery'}),node_id:'commit'};
 await f.service.runtime.recordHostToolIntent(run.run_id,{...args,contract,input:{}});const delivered=await new HostToolRunner({registry:{[contract.id]:f.domain}}).execute(contract,{}, {run_id:run.run_id,node_id:'commit',attempt_id:args.attempt_id,workspace:f.workspace,permissions:{access:'bounded_write',allowed_paths:['.']}});const output={kind:'host_tool_output',output:delivered.output};delivered.receipt.output_ref={...await f.service.runtime.runs.saveExecutorResult(run.run_id,args.attempt_id,output),bytes:Buffer.byteLength(canonicalJSON(output))};await f.service.runtime.recordHostToolReceipt(run.run_id,{...args,receipt:delivered.receipt});
 const completion={status:'succeeded',summary:'',structured_output:delivered.output,artifacts:[],evidence:[{kind:'host_tool',tool:contract.id,sha256:delivered.receipt.output_sha256}],changed_paths:delivered.receipt.effects.changed_paths,outside_paths:delivered.receipt.effects.outside_paths};
 await assert.rejects(f.service.runtime.completeNode(run.run_id,{...args,completion}),{code:'SCOPE_VIOLATION'});await assert.rejects(f.service.runtime.completeNode(run.run_id,{...args,completion:{...completion,outside_paths:[]}}),{code:'HOST_TOOL_COMPLETION_CONFLICT'});
 const before=await f.service.runtime.runs.read(run.run_id);await f.service.call('adopt_run',{run_id:run.run_id,expected_sequence:before.sequence,reason:'Offline exact receipt recovery'},{human:true});const selection={run_id:run.run_id,node_id:'commit',attempt_id:args.attempt_id,receipt_sha256:digest(canonicalJSON(delivered.receipt))};
 await assert.rejects(f.service.call('collect_host_tool',selection,{human:true}),{code:'HOST_STORAGE_CAPABILITY'});assert.equal(f.calls(),1);
 f.domain.attestation.storage_capabilities={...f.capabilities,write_files:f.files.slice(1)};await assert.rejects(f.service.call('collect_host_tool',selection,{human:true}),{code:'SCOPE_VIOLATION'});
 f.domain.attestation.storage_capabilities=f.capabilities;await assert.rejects(f.service.call('collect_host_tool',{...selection,receipt_sha256:digest('wrong')},{human:true}),{code:'HOST_TOOL_COLLECTION_CONFLICT'});
 const originalActor=f.host.mainIdentity;f.host.mainIdentity=()=>({session_id:'different-actor'});await assert.rejects(f.service.call('collect_host_tool',selection,{human:true}),{code:'PI_EXTERNAL_HOST_PIN'});f.host.mainIdentity=originalActor;
 f.domain.attestation.evidence_sha256=digest('different-broker');await assert.rejects(f.service.call('collect_host_tool',selection,{human:true}),{code:'HOST_STORAGE_AUTHORIZATION'});f.domain.attestation.evidence_sha256=digest('fixture-qualification');
 await assert.rejects(f.service.call('collect_host_tool',{...selection,attempt_id:'not-the-attempt'},{human:true}),{code:'HOST_TOOL_COLLECTION'});
 const resultPath=join(f.service.runtime.runs.directory(run.run_id),delivered.receipt.output_ref.artifact),originalBytes=await readFile(resultPath);await writeFile(resultPath,'{}');await assert.rejects(f.service.call('collect_host_tool',selection,{human:true}),{code:'EXECUTOR_RESULT_CORRUPT'});await writeFile(resultPath,originalBytes);
 const collected=await f.service.call('collect_host_tool',selection,{human:true});assert.equal(collected.implementation_invoked,false);assert.equal(collected.model_calls,0);assert.equal(f.calls(),1);let r=await f.service.runtime.runs.read(run.run_id);assert.equal(r.state.status,'paused');assert.equal(r.state.nodes.commit.status,'succeeded');assert.equal(r.state.nodes.commit.attempts.length,1);assert.deepEqual(r.state.nodes.commit.attempts[0].host_tool.receipt,delivered.receipt);assert.equal(r.state.nodes.commit.attempts[0].host_tool.storage_authorization.receipt_sha256,selection.receipt_sha256);
 await f.service.call('continue',{run_id:run.run_id});await settle(f.service,run.run_id);r=await f.service.runtime.runs.read(run.run_id);assert.equal(r.state.status,'succeeded');assert.equal(f.calls(),2,'Only downstream deterministic node executes');assert.equal(f.requests.length,0);assert.equal(f.mainRequests.length,0);assert.equal(await readFile(f.files[0],'utf8'),'database-write-2');
});
test('private storage declarations reject relative, root and sibling traversal scopes',()=>{
 assert.throws(()=>validateHostStorageCapabilities({write_files:['relative.sqlite'],write_directories:[]}),{code:'HOST_STORAGE_CAPABILITY'});assert.throws(()=>validateHostStorageCapabilities({write_files:[],write_directories:[parse(process.cwd()).root]}),{code:'HOST_STORAGE_CAPABILITY'});assert.throws(()=>requireHostStorageEffects([join(process.cwd(),'sibling','secret')],{write_files:[],write_directories:[join(process.cwd(),'owned')]}),{code:'SCOPE_VIOLATION'});
});
