import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, mkdir, writeFile, readFile, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, resolve, sep } from 'node:path';
import { randomUUID } from 'node:crypto';
import * as sdk from '@earendil-works/pi-coding-agent';
import * as ai from '@earendil-works/pi-ai/compat';
import { PiSdkHost } from '../lib/pi-sdk-host.mjs';
import { PiCawService } from '../lib/service.mjs';
import { resolveBinding } from '../lib/models.mjs';

test('real offline Pi Role retirement and persistent thread continuation use separate storage',{timeout:20000},async t=>{
  const root=await mkdtemp(join(tmpdir(),'pi-caw-session-lifetime-')),cwd=join(root,'workspace'),agentDir=join(root,'agent');
  await mkdir(cwd);await mkdir(agentDir);
  await writeFile(join(agentDir,'settings.json'),JSON.stringify({packages:[],retry:{enabled:false}}));
  const faux=ai.fauxProvider({provider:`session-lifetime-${randomUUID()}`,models:[{id:'worker',reasoning:false}],tokensPerSecond:0});
  const submit=text=>[ai.fauxAssistantMessage(ai.fauxToolCall('caw_submit_result',{result:{result:text},summary:text}),{stopReason:'toolUse'}),ai.fauxAssistantMessage('Submitted.')];
  faux.setResponses([...submit('Role result'),ai.fauxAssistantMessage('Missing semantic submission.'),...submit('First thread result'),...submit('Continued thread result')]);
  const runtime=await sdk.ModelRuntime.create({authPath:join(agentDir,'auth.json'),modelsPath:null,refreshOnCreate:false});
  runtime.registerNativeProvider(faux.provider);await runtime.refresh({allowNetwork:false});
  const parent=sdk.SessionManager.create(cwd,join(agentDir,'sessions'));parent.appendMessage(ai.fauxAssistantMessage('Parent history.'));
  const context={cwd,sessionManager:parent,modelRegistry:new sdk.ModelRegistry(runtime),model:faux.getModel(),thinkingLevel:'off',isProjectTrusted:()=>false};
  const host=new PiSdkHost({sdk,Type:ai.Type,supportedThinking:ai.getSupportedThinkingLevels,agentDir,getContext:()=>context});
  host.modelRuntimes.set(faux.getModel().provider,runtime);
  const service=await new PiCawService({directory:join(root,'state'),host}).initialize();
  assert.throws(()=>host.setExecutionDirectory(join(agentDir,'sessions','private')),{code:'PI_SESSION_STORAGE'});
  t.after(async()=>{await service.close();assert.ok(resolve(root).startsWith(resolve(tmpdir())+sep));await rm(root,{recursive:true,maxRetries:3,retryDelay:100});});
  const binding=resolveBinding({provider:faux.getModel().provider,model_id:'worker',thinking:'off'},host.catalog());
  service.workbench.roleProfile=async()=>({id:'review',name:'Review',status:'ready',enabled:true,provider_available:true,binding,
    access:'read_only',revision_hash:'a'.repeat(64),instructions:'Submit the declared semantic result.'});
  const role=await service.launchRole({role_id:'review',task:'Review',workspace:cwd});await Promise.all(service.roleTasks.values());
  await assert.rejects(readFile(role.session_file),{code:'ENOENT'});
  assert.equal(JSON.parse(await readFile(join(service.directory,'role-runs',`${role.role_run_id}.json`),'utf8')).result.result.result,'Role result');
  const failed=await service.launchRole({role_id:'review',task:'Fail',workspace:cwd});
  await Promise.allSettled(service.roleTasks.values());await service.roleRetention.sweep();
  assert.ok(await readFile(failed.session_file));assert.equal(service.lastRoleError.session_id,failed.session_id);
  const schema={type:'object',properties:{result:{type:'string'}},required:['result'],additionalProperties:false};
  const request={kind:'thread',run_id:randomUUID(),node_id:'first',name:'Persistent',binding,workspace:cwd,access:'read_only',allowed_paths:[],resources:[],strict:true,schema};
  const first=await host.createTask(request);
  assert.throws(()=>host.setExecutionDirectory(join(root,'relocated')),{code:'PI_SESSION_STORAGE_BUSY'});
  await first.run({prompt:'Start a persistent thread.',schema});await host.releaseTask(first);
  assert.equal(first.session_storage,'persistent');assert.ok(resolve(first.session_file).startsWith(resolve(agentDir,'sessions')+sep));
  const continued=await host.createTask({...request,node_id:'next',session_id:first.session_id,session_file:first.session_file});
  assert.equal(continued.session_id,first.session_id);await continued.run({prompt:'Continue this thread.',schema});await host.releaseTask(continued);
  const saved=await readFile(first.session_file,'utf8');assert.match(saved,/First thread result/);assert.match(saved,/Continued thread result/);
  const history=await sdk.SessionManager.listAll(join(agentDir,'sessions'));
  assert.ok(history.some(item=>item.id===first.session_id));assert.ok(history.some(item=>item.id===parent.getSessionId()));
  assert.equal(history.some(item=>item.id===failed.session_id || item.id===role.session_id),false);
  assert.equal(parent.getEntries().filter(entry=>entry.type==='message').length,1);
});
