import test from 'node:test';
import assert from 'node:assert/strict';
import {bindingPointers,resolveBindings} from '../core/workflow-bindings.mjs';
import {projectNodeContext} from '../core/workflow-context-projection.mjs';
import {validateWorkflowGraph} from '../core/workflow-validator.mjs';
import {workflow,agent} from './fixtures.mjs';
const optional={path:'/nodes/author/output/result/draft',omit_if_missing:true};
const contract={id:'commit',identity:{name:'commit',version:'1',sha256:'a'.repeat(64)},argv:[],input_schema:{type:'object',additionalProperties:false,required:['files'],properties:{files:{type:'array',maxItems:3,items:{type:'string'}},draft:{type:'object',additionalProperties:false,properties:{title:{type:'string',maxLength:100}},required:[]}}},output_schema:{type:'object',additionalProperties:false,required:['succeeded'],properties:{succeeded:{type:'boolean'}}},env_allow:[],permissions:{network:false,read_paths:['.'],write_paths:[]},output_cap_bytes:4096,deadline_ms:1000,idempotency:{mode:'safe'}};
function graph(){const author=agent('author');author.outputs_schema={type:'object',additionalProperties:false,properties:{result:{type:'object',additionalProperties:false,required:['files'],properties:{files:contract.input_schema.properties.files,draft:contract.input_schema.properties.draft}}},required:['result']};const commit={...agent('commit-node',{kind:'tool',tool:'commit'}),type:'tool',input_bindings:{files:'/nodes/author/output/result/files',draft:optional},outputs_schema:contract.output_schema,completion_contract:{on_missing:'block',outcome:'validated_artifact',fail_on_false:['succeeded']}};const g=workflow([author]);g.nodes=[{id:'start',type:'start'},author,commit,{id:'end',type:'end'}];g.edges=g.nodes.slice(0,-1).map((node,index)=>({id:`e${index}`,source:node.id,target:g.nodes[index+1].id}));g.finalization={required:true,node_id:'commit-node'};g.host_tools=[contract];g.outputs_schema=contract.output_schema;return g;}
test('qualified optional Host fields are omitted only when absent; empty, false and null values remain explicit',()=>{assert.deepEqual(bindingPointers(optional),[optional.path]);const scope={optionalHostInputs:new Set(['draft'])};assert.deepEqual({...resolveBindings({draft:optional},{nodes:{author:{output:{result:{files:[]}}}}},scope)},{});for(const value of [{},false,null,''])assert.deepEqual({...resolveBindings({draft:optional},{nodes:{author:{output:{result:{draft:value}}}}},scope)},{draft:value});assert.throws(()=>resolveBindings({draft:optional},{nodes:{}}),{code:'BINDING_OMISSION_SCOPE'});assert.throws(()=>resolveBindings({files:'/nodes/author/output/result/files'},{nodes:{}}),{code:'BINDING_MISSING'});for(const extra of [{default:{}},{coalesce:['/inputs/draft']},{pluck:'draft'},{omit_if_missing:false}])assert.throws(()=>bindingPointers({...optional,...extra}),{code:'BINDING_SCHEMA'});});
test('runtime context qualifies omissions from the exact pinned Host input contract and never suppresses required inputs',()=>{const g=graph(),node=g.nodes[2],context={inputs:{},nodes:{author:{output:{result:{files:[]}}}}};assert.deepEqual({...projectNodeContext(node,g,context).inputs},{files:[]});context.nodes.author.output.result.draft={title:'New semantic title'};assert.deepEqual(projectNodeContext(node,g,context).inputs.draft,{title:'New semantic title'});const required=structuredClone(g);required.host_tools[0].input_schema.required.push('draft');assert.throws(()=>projectNodeContext(node,required,context),{code:'BINDING_OMISSION_SCOPE'});const missing={inputs:{},nodes:{author:{output:{result:{}}}}};assert.throws(()=>projectNodeContext(node,g,missing),{code:'BINDING_MISSING'});assert.throws(()=>projectNodeContext({...node,type:'agent',executor:{kind:'provider',provider_id:'worker'}},g,context),{code:'BINDING_OMISSION_SCOPE'});});
test('graph validation rejects omit selectors on required, unknown or Agent inputs before launch',()=>{const context={providers:[{id:'worker',enabled:true,kind:'function',capabilities:{read:true}}],host_tools:['commit']},g=graph(),valid=validateWorkflowGraph(g,context);assert.ok(!valid.errors.some(error=>error.code==='BINDING_OMISSION_SCOPE'||error.code==='BINDING_SCHEMA'),JSON.stringify(valid.errors));for(const alter of [g=>g.host_tools[0].input_schema.required.push('draft'),g=>g.nodes[2].input_bindings.unknown=optional,g=>g.nodes[1].input_bindings.draft={path:'/inputs/task',omit_if_missing:true}]){const bad=structuredClone(g);alter(bad);assert.ok(validateWorkflowGraph(bad,context).errors.some(error=>error.code==='BINDING_OMISSION_SCOPE'));}});
