import test from 'node:test';
import assert from 'node:assert/strict';
import {sourceContractIndex,RESOLVED_SEMANTIC_OUTPUT_RULE} from '../core/skill-import/source-contracts.mjs';
import {validateData} from '../core/workflow-data-schema.mjs';
import {lowerSemanticBlueprint} from '../core/authoring/workflow-forge.mjs';
import {sourceSectionInventory} from '../core/skill-import/source-dispositions.mjs';
import {PREVIOUS_SEMANTIC_BLUEPRINT_CONTRACT} from '../core/authoring/blueprint-contract.mjs';
import {canonicalJSON,digest} from '../core/workflow-revisions.mjs';
const schema={type:'object',additionalProperties:false,required:['answer','files'],properties:{answer:{type:'string',minLength:1,maxLength:20000},draft:{type:'object',additionalProperties:false,required:['title'],properties:{title:{type:'string',minLength:1,maxLength:100},segments:{type:'array',minItems:1,maxItems:20,uniqueItems:true,items:{type:'object',additionalProperties:false,required:['minutes'],properties:{minutes:{type:'integer',minimum:1,maximum:90},example:{type:'string',maxLength:400}}}}}},files:{type:'array',minItems:0,maxItems:3,items:{type:'object',additionalProperties:false,required:['path'],properties:{path:{type:'string',minLength:1,maxLength:300}}}}}};
function resources(value=schema){return {'source/SKILL.md':Buffer.from('# Explain\n\nExplain the current question.\n'),'source/author-result.schema.json':Buffer.from(JSON.stringify(value,null,2))};}
function lower(value,contractPointer='',{operation='read',instructions='Explain the current question and return newly authored content.',name='answer'}={}){const files=resources(value),contract=sourceContractIndex(files).contracts.find(item=>item.json_pointer===contractPointer),sections=sourceSectionInventory(files),blueprint={contract:PREVIOUS_SEMANTIC_BLUEPRINT_CONTRACT,purpose:'Explain the question',source_dispositions:sections.map(section=>({section_id:section.section_id,disposition:'workflow',activity_keys:['author'],note:'Bounded explanation'})),data_types:[],activities:[{key:'author',kind:'work',ownership:'isolated_worker',operation,instructions,source_sections:sections.map(section=>section.section_id),consumes:[],produces:[{name,shape:{kind:'text',type_ref:'',values:[]},contract_ref:contract.contract_id}],on_missing:'block',outcome:'artifact'}],approvals:[],sequences:[],parallels:[],choices:[],root:'author',semantic_rules:[],requirement_assignments:[]};return lowerSemanticBlueprint({workflow:{id:'explain',requirements:{}}},files,blueprint).nodes.find(node=>node.semantic_key==='author');}
test('explicit schema contracts preserve full and per-property bounds/optionality with exact pins; ordinary JSON and Python guesses are not schema authority',()=>{const files=resources(),bytes=files['source/author-result.schema.json'];files['source/data.json']=Buffer.from(JSON.stringify(schema));files['source/validator.py']=Buffer.from("required = ['answer']\nif not str(spec.get('answer')).strip():\n    raise ValueError('empty')\n");const index=sourceContractIndex(files),full=index.contracts.find(item=>item.json_pointer==='');assert.equal(full.authority,'interface');assert.equal(full.status,'resolved');assert.equal(full.semantic_output,true);assert.deepEqual(full.output_schema,schema);assert.equal(full.resource_sha256,digest(bytes));assert.equal(full.schema_sha256,digest(canonicalJSON(schema)));assert.equal(full.output_schema.properties.draft.required.includes('segments'),false);const answer=index.contracts.find(item=>item.json_pointer==='/properties/answer');assert.deepEqual(answer.output_schema,schema.properties.answer);answer.output_schema.maxLength=1;assert.equal(full.output_schema.properties.answer.maxLength,20000);assert.ok(!index.contracts.some(item=>item.resource==='source/data.json'));assert.equal(index.contracts.find(item=>item.resource.endsWith('.py')).status,'candidate');});
test('malformed/unsupported explicitly named schemas fail visibly rather than falling back to inferred interfaces',()=>{for(const value of [Buffer.from('{ broken'),Buffer.from(JSON.stringify({type:'object',oneOf:[]})),Buffer.from(JSON.stringify({type:['string','null']})),Buffer.from([0xff])])assert.throws(()=>sourceContractIndex({'source/result.schema.json':value}),error=>error.code==='SOURCE_CONTRACT_SCHEMA'&&error.details.resource==='source/result.schema.json');});
test('forge emits exact semantic schema values and rejects optional/nested/renamed Host identity fields',()=>{const answer=lower(schema,'/properties/answer');assert.deepEqual(answer.outputs_schema,{type:'object',properties:{answer:schema.properties.answer},required:['answer'],additionalProperties:false});const full=lower(schema,'',{operation:'write',instructions:'Create the new files. Return newly chosen relative artifact paths.',name:'result'});assert.deepEqual(full.outputs_schema.properties.result,schema);assert.equal(full.outputs_schema.properties.result.required.includes('draft'),false);assert.throws(()=>lower(schema,'',{name:'result'}),/Host-owned/);for(const field of ['noteId','sourceHash','receipt','revision']){const bad=structuredClone(schema);bad.properties.draft.properties[field]={type:'string',maxLength:100};assert.throws(()=>lower(bad,'',{operation:'write',instructions:'Return newly chosen relative artifact paths.',name:'result'}),/Host-owned/);const renamed={type:'object',additionalProperties:false,properties:{[field]:{type:'string',maxLength:100}},required:[]};assert.throws(()=>lower(renamed,`/properties/${field}`,{name:'answer'}),/Host-owned/);}});
test('semester semantic revisit labels lower without model IDs and state-only empty file lists require no write authority',()=>{const closed=properties=>({type:'object',additionalProperties:false,required:[],properties}),semester=closed({draft:closed({sessions:{type:'array',minItems:1,maxItems:840,items:closed({revisits:{type:'array',maxItems:100,items:closed({concept:{type:'string',minLength:1,maxLength:4096},progression:{enum:['complexity','transfer']},note:{type:'string',minLength:1,maxLength:4096}})}})}}),files:{type:'array',minItems:0,maxItems:0,items:closed({path:{type:'string',minLength:1,maxLength:4096}})}});semester.required=['draft','files'];const author=lower(semester,'',{name:'result'});assert.deepEqual(author.outputs_schema.properties.result,semester);const legacy=structuredClone(semester),properties=legacy.properties.draft.properties.sessions.items.properties.revisits.items.properties;properties.conceptId=properties.concept;delete properties.concept;assert.throws(()=>lower(legacy,'',{name:'result'}),/Host-owned/);});

test('resolved schema review facts limit generic conditional methods without weakening exact bounds or waiving conflicting source requirements',()=>{
  const fileProduct=structuredClone(schema);fileProduct.properties.files.minItems=1;
  const files=resources(fileProduct);files['source/SKILL.md']=Buffer.from('# File product\n\nCreate the requested files. Generic method: an empty array is for a state-only draft; otherwise return the new files.\n');
  const bytes=digest(files['source/author-result.schema.json']),index=sourceContractIndex(files),full=index.contracts.find(item=>item.json_pointer==='');
  assert.equal(index.resolved_semantic_output_rule,RESOLVED_SEMANTIC_OUTPUT_RULE);
  assert.match(index.resolved_semantic_output_rule,/selected kind\/mode/);
  assert.match(index.resolved_semantic_output_rule,/source\/Host contract inconsistency/);
  assert.deepEqual(full.output_schema,fileProduct);assert.equal(full.resource_sha256,bytes);
  assert.throws(()=>validateData({answer:'New explanation',files:[]},full.output_schema),{code:'DATA_INVALID'});
  validateData({answer:'New explanation',files:[{path:'sources/new.tex'}]},full.output_schema);
  assert.equal(digest(files['source/author-result.schema.json']),bytes);
});
