import { useContext, useEffect, useState } from 'react';
import { RoleActions } from './role-actions';
import { api, Details, Field, JsonField, Select, FormValidContext, uid, useLocale, type Json } from './shared';

export function BindingPicker({ models, binding, change }: { models: Json[], binding: Json | null, change: (next: Json | null) => void }) {
  const t = useLocale();
  const identity = binding ? `${binding.provider}/${binding.model_id}` : '';
  const model = models.find(item => item.provider === binding?.provider && item.model_id === binding?.model_id);
  return <div className="binding-picker"><Select label={t('Pi 模型（必须明确选择）', 'Pi model (explicit selection required)')} value={identity}
    options={[{ value: '', label: t('尚未绑定', 'Unbound') }, ...models.map(item => ({ value: `${item.provider}/${item.model_id}`, label: `${item.name} · ${item.provider}/${item.model_id}` }))]}
    onChange={value => { if (!value) change(null); else { const selected = models.find(item => `${item.provider}/${item.model_id}` === value); if (!selected) throw new Error('Selected Pi model disappeared from the catalog'); change({ provider: selected.provider, model_id: selected.model_id, thinking: '' }); } }}/>
    {binding && <Select label={t('思考强度（必须明确选择）', 'Thinking (explicit selection required)')} value={binding.thinking}
      options={[{ value: '', label: t('请选择思考强度', 'Choose thinking') }, ...(model?.thinking_levels ?? []).map((value: string) => ({ value, label: value }))]}
      onChange={thinking => change({ provider: binding.provider, model_id: binding.model_id, thinking })}/>}
    {binding && !model && <p role="alert">{t('此绑定不在当前 Pi 对话的可用目录中。请明确重新绑定。', 'This binding is unavailable in the current Pi conversation catalog. Rebind explicitly.')}</p>}
    {binding?.fingerprint && model && binding.fingerprint !== model.fingerprint && <p role="alert">{t('模型契约已变化，请重新选择模型并保存。', 'The model contract changed. Select the model again and save.')}</p>}
  </div>;
}

export function PiSettings({ configuration, act, busy, reload, onDirty }: { configuration: Json, act: (work: () => Promise<any>) => void, busy: number, reload: () => Promise<void>, onDirty: (dirty: boolean) => void }) {
  const t = useLocale();
  const valid = useContext(FormValidContext);
  const [settings, setSettings] = useState<Json>(() => structuredClone(configuration.settings));
  const [revision, setRevision] = useState(configuration.revision);
  const [dirty, setDirty] = useState(false);
  useEffect(() => { setSettings(structuredClone(configuration.settings)); setRevision(configuration.revision); setDirty(false); }, [configuration.revision]);
  useEffect(() => { const handler = (event: BeforeUnloadEvent) => { if (dirty) event.preventDefault(); }; window.addEventListener('beforeunload', handler); return () => window.removeEventListener('beforeunload', handler); }, [dirty]);
  useEffect(() => { onDirty(dirty); return () => onDirty(false); }, [dirty]);
  const patch = (next: Json) => { setSettings(next); setDirty(true); };
  const providers: Json[] = settings.providers;
  const roles: Json[] = settings.roles;
  const global = settings.global ?? { enabled: true, console_title: 'pi-CAW', max_prompt_chars: 80000 };
  return <main className="detail-page scroll settings-page"><div className="page-heading"><div><span className="eyebrow">{t('Pi 对话目录', 'Pi conversation catalog')}</span><h1>{t('Role 与 Provider 设置', 'Role and Provider settings')}</h1><p>{t('Main 沿用当前 Pi 对话。子模型和思考强度留空，直到你明确选择；Pi 管理认证和模型连接。', 'Main follows the current Pi conversation. Child models and thinking stay empty until explicitly selected; Pi manages authentication and model connections.')}</p></div><div className="actions"><button disabled={busy > 0 || dirty} onClick={() => act(reload)}>{t('刷新目录', 'Refresh catalog')}</button><button className="primary" disabled={busy > 0 || !dirty || !valid} onClick={() => act(async () => { const result = await api('save_settings', { settings, expected_revision: revision }); setSettings(result.settings); setRevision(result.revision); setDirty(false); await reload(); })}>{t('保存设置', 'Save settings')}{dirty ? ' *' : ''}</button></div></div>
    <h2>{t('全局设置','Global settings')}</h2><label className="check"><input type="checkbox" checked={global.enabled} onChange={event=>patch({...settings,global:{...global,enabled:event.target.checked}})}/>{t('启用 Roles 与 Workflows','Enable Roles and Workflows')}</label><Field label={t('工作台标题','Workbench title')} value={global.console_title} onChange={console_title=>patch({...settings,global:{...global,console_title}})}/><label className="field">{t('编译指令字符上限（1000–200000）','Compiled instruction character limit (1000–200000)')}<input type="number" min={1000} max={200000} step={1000} value={global.max_prompt_chars} onChange={event=>patch({...settings,global:{...global,max_prompt_chars:Number(event.target.value)}})}/></label>
    <h2>{t('Provider · 子 Agent 模型绑定', 'Providers · child Agent model bindings')}</h2><div className="settings-grid">{providers.map((provider, index) => <section className="settings-card" key={index}><div className="panel-heading"><h3>{provider.name || provider.id}</h3><button className="danger" onClick={() => act(async () => { if (roles.some(role => role.provider_id === provider.id) || routingUsesProvider(settings.routing,provider.id)) throw new Error(t('此 Provider 仍被 Role 或路由引用，请先解除绑定。', 'A Role or route still references this Provider; remove those bindings first.')); patch({ ...settings, providers: providers.filter((_, i) => i !== index) }); })}>{t('移除', 'Remove')}</button></div>
      <Field label="Provider ID" value={provider.id} onChange={id => patch({ ...settings, providers: providers.map((p, i) => i === index ? { ...p, id } : p) })}/><Field label={t('名称', 'Name')} value={provider.name} onChange={name => patch({ ...settings, providers: providers.map((p, i) => i === index ? { ...p, name } : p) })}/>
      <label className="check"><input type="checkbox" checked={provider.enabled} onChange={event => patch({ ...settings, providers: providers.map((p, i) => i === index ? { ...p, enabled: event.target.checked } : p) })}/>{t('启用', 'Enabled')}</label>
      <Field label={t('适用场景与能力说明','Task fit and capability description')} value={provider.description??''} multiline onChange={description=>patch({...settings,providers:providers.map((p,i)=>i===index?{...p,description}:p)})}/><label className="check"><input type="checkbox" checked={provider.requires_user_approval??false} onChange={event=>patch({...settings,providers:providers.map((p,i)=>i===index?{...p,requires_user_approval:event.target.checked}:p)})}/>{t('每次调用需要人工批准','Require human approval for each call')}</label><p className="muted">{t('声明此 Provider 的允许能力；实际执行仍须通过 Pi Host 能力检查。','Declare this Provider’s allowed capabilities. Actual execution must also pass Pi Host capability checks.')}</p>{(['read','write','background'] as const).map(capability=><label className="check" key={capability}><input type="checkbox" checked={provider.capabilities?.[capability]??true} onChange={event=>patch({...settings,providers:providers.map((p,i)=>i===index?{...p,capabilities:{read:true,write:true,background:true,...p.capabilities,[capability]:event.target.checked}}:p)})}/>{({read:t('读取','Read'),write:t('写入','Write'),background:t('后台执行','Background execution')})[capability]}</label>)}
      <BindingPicker models={configuration.models} binding={provider.binding} change={binding => patch({ ...settings, providers: providers.map((p, i) => i === index ? { ...p, binding } : p) })}/>
    </section>)}</div><button onClick={() => patch({ ...settings, providers: [...providers, { id: uid('provider'), name: t('新 Provider', 'New provider'), enabled: false, binding: null, description: '', requires_user_approval: false, capabilities: { read: true, write: true, background: true } }] })}>＋ {t('添加 Provider', 'Add provider')}</button>
    <h2>{t('Role · 普通任务角色', 'Roles · ordinary task profiles')}</h2><div className="settings-grid">{roles.map((role, index) => { const update = (fields: Json) => patch({ ...settings, roles: roles.map((item, i) => i === index ? { ...item, ...fields } : item) }); return <section className="settings-card" key={index}><div className="panel-heading"><h3>{role.name}</h3><button className="danger" onClick={() => patch({ ...settings, roles: roles.filter((_, i) => i !== index) })}>{t('移除 Role', 'Remove role')}</button></div><Field label="Role ID" value={role.id} onChange={id => update({ id })}/><Field label={t('名称', 'Name')} value={role.name} onChange={name => update({ name })}/><Field label={t('说明', 'Description')} value={role.description??''} multiline onChange={description => update({ description })}/><Field label={t('自动分配条件与职责','Automatic assignment triggers and responsibilities')} value={role.role_instructions??''} multiline onChange={role_instructions => update({ role_instructions })}/>{role.route !== undefined && <Select label={t('角色模式','Role mode')} value={role.route} options={['delegate','audit','full']} onChange={route=>update({route})}/>} <JsonField label={t('标签','Tags')} value={role.tags??[]} onChange={tags=>update({tags})}/><Details title={t('触发条件、职责与来源', 'Triggers, responsibilities, and origin')} value={{ route: role.route, tags: role.tags, role_instructions: role.role_instructions, source_metadata: role.source_metadata }}/><label className="check"><input type="checkbox" checked={role.enabled} onChange={event => update({ enabled: event.target.checked })}/>{t('启用', 'Enabled')}</label><Select label={t('Provider 绑定', 'Provider binding')} value={role.provider_id ?? ''} options={[{ value: '', label: t('尚未绑定', 'Unbound') }, ...providers.map(provider => ({ value: provider.id, label: provider.name }))]} onChange={provider_id => update({ provider_id: provider_id || null })}/><Select label={t('访问权限', 'Access')} value={role.access} options={['read_only', 'bounded_write']} onChange={access => update({ access })}/><Field label={t('角色指令', 'Role instructions')} value={role.prompt} multiline onChange={prompt => update({ prompt })}/><RoleActions key={revision} roleId={role.id} act={act} disabled={dirty}/></section>; })}</div><button onClick={() => patch({ ...settings, roles: [...roles, { id: uid('role'), name: t('新 Role', 'New role'), enabled: false, provider_id: null, access: 'read_only', prompt: t('按本次任务和上下文完成工作，并返回结果与验证证据。', 'Complete the task from its context and return the result with verification evidence.') }] })}>＋ {t('添加 Role', 'Add role')}</button>
    <h2>{t('职责路由', 'Responsibility routing')}</h2><JsonField label={t('完整职责路由、生成和审核设置', 'Complete responsibility, generation, and review routing')} value={settings.routing} onChange={routing => patch({ ...settings, routing })}/><Details title={t('当前 Pi 模型目录', 'Current Pi model catalog')} value={configuration.models}/>
  </main>;
}

function routingUsesProvider(value:unknown,id:string):boolean {
 if(value===id)return true;
 if(value&&typeof value==='object')return Object.entries(value).some(([key,item])=>key!=='instructions'&&routingUsesProvider(item,id));
 return false;
}
