import { useContext, useState } from 'react';
import { api, Details, Field, JsonField, FormValidContext, useLocale, type Json } from './shared';
export function RoleActions({ roleId, revision, act, disabled = false }: { roleId: string, revision?: string, act: (work: () => Promise<any>) => void, disabled?: boolean }) {
  const t = useLocale(), valid = useContext(FormValidContext);
  const [context,setContext]=useState(''),[constraints,setConstraints]=useState(''),[verification,setVerification]=useState('');
  const [task, setTask] = useState(''), [workspace, setWorkspace] = useState(''), [paths, setPaths] = useState<Json | string[]>([]);
  const [compiled, setCompiled] = useState<Json | null>(null), [launched, setLaunched] = useState<Json | null>(null), [busy, setBusy] = useState(false), [copied, setCopied] = useState(false);
  const controlled = (work: () => Promise<void>) => act(async () => { setBusy(true); try { await work(); } finally { setBusy(false); } });
  const reference = { context, constraints, verification, role_id: roleId, workflow_id: roleId, ...(revision ? { revision_hash: revision } : {}) };
  return <details className="role-actions"><summary>{t('编译指令与分配任务', 'Compile instructions and assign a task')}</summary><p>{t('Role 分配一个 Pi 子 Agent，不创建 Workflow Run。先保存当前角色，再编译或启动；子模型需要明确绑定。', 'A Role assigns one Pi child Agent without creating a Workflow Run. Save the role before compiling or launching; a child model requires an explicit binding.')}</p>
    <Field label={t('本次任务', 'Task for this assignment')} value={task} multiline onChange={value => { setTask(value); setCompiled(null); setCopied(false); }}/><details><summary>{t('上下文、约束与验证要求','Context, constraints, and verification')}</summary><Field label={t('上下文','Context')} value={context} multiline onChange={value=>{setContext(value);setCompiled(null);}}/><Field label={t('约束与所有权','Constraints and ownership')} value={constraints} multiline onChange={value=>{setConstraints(value);setCompiled(null);}}/><Field label={t('验证要求','Verification requirements')} value={verification} multiline onChange={value=>{setVerification(value);setCompiled(null);}}/></details><button disabled={disabled || busy || !task.trim()} onClick={() => controlled(async () => { setCompiled(await api('role_template', { ...reference, task })); setCopied(false); })}>{t('编译角色指令', 'Compile role instructions')}</button>
    {compiled && <><Details title={t('完整指令与固定绑定', 'Complete instructions and fixed binding')} value={compiled}/><button disabled={busy} onClick={() => controlled(async () => { if (!navigator.clipboard) throw new Error('Clipboard is unavailable in this browser. Open the complete instruction preview to copy the text.'); await navigator.clipboard.writeText(compiled.instructions); setCopied(true); })}>{copied ? t('已复制', 'Copied') : t('复制编译指令', 'Copy compiled instructions')}</button></>}
    <Field label={t('任务工作目录（绝对路径）', 'Task workspace (absolute path)')} value={workspace} onChange={setWorkspace}/><JsonField label={t('明确允许写入的路径', 'Explicit allowed write paths')} value={paths} onChange={setPaths}/><button className="primary" disabled={disabled || busy || !valid || !task.trim() || !workspace.trim()} onClick={() => controlled(async () => setLaunched(await api('launch_role', { ...reference, task, workspace, allowed_paths: paths })))}>{busy ? t('正在处理…', 'Working…') : t('启动此 Role 的子 Agent', 'Launch this Role’s child Agent')}</button>{launched && <Details title={t('实际 Pi 会话身份与启动状态', 'Actual Pi session identity and launch state')} value={launched}/>}
  </details>;
}
